class: Workflow
cwlVersion: v1.0
id: qc_collapsed_bam
label: qc_collapsed_bam
$namespaces:
  sbg: 'https://www.sevenbridges.com/'
inputs:
  - id: reference
    type: File
    secondaryFiles:
      - ^.fasta.fai
      - ^.dict
    'sbg:x': -1255.3157958984375
    'sbg:y': 246.26315307617188
  - id: pool_b_target_intervals
    type: File
    label: pool_b_target_intervals
    'sbg:x': -1380.0771484375
    'sbg:y': -176.342529296875
  - id: pool_a_target_intervals
    type: File
    label: pool_a_target_intervals
    'sbg:x': -1407.2725830078125
    'sbg:y': -725.6703491210938
  - id: collapsed_bam
    type:
      - File
      - type: array
        items: File
    label: collapsed_bam
    secondaryFiles:
      - ^.bai
    'sbg:x': -1304.26318359375
    'sbg:y': 712
  - id: group_reads_by_umi_bam
    type:
      - File
      - type: array
        items: File
    label: group_reads_by_umi_bam
    doc: Input BAM file generated by GroupReadByUmi.
    'sbg:x': -913.631591796875
    'sbg:y': -131.26315307617188
  - id: pool_a_bait_intervals
    type: File?
    label: pool_a_bait_intervals
    doc: 'Optional set of intervals over which to restrict analysis. [Optional].'
    'sbg:x': -1419.413818359375
    'sbg:y': -885.5172119140625
  - id: pool_b_bait_intervals
    type: File?
    label: pool_b_bait_intervals
    doc: 'Optional set of intervals over which to restrict analysis. [Optional].'
    'sbg:x': -1393.6268310546875
    'sbg:y': -352.0533142089844
  - id: json
    type: boolean?
    doc: Also output data in JSON format.
    'sbg:x': -50.14529037475586
    'sbg:y': 668.078369140625
  - id: plot
    type: boolean?
    doc: Also output plots of the data.
    'sbg:x': -37.99789047241211
    'sbg:y': 828.6326904296875
  - id: minor_threshold
    type: float?
    doc: Minor contamination threshold for bad sample.
    'sbg:x': -20.255456924438477
    'sbg:y': 1140.8995361328125
  - id: coverage_threshold
    type: int?
    doc: Samples with Y chromosome above this value will be considered male.
    'sbg:x': -28.91999626159668
    'sbg:y': 1299.155029296875
  - id: hsmetrics_minimum_mapping_quality
    type: int?
    'sbg:x': -1416.0538330078125
    'sbg:y': -1003.3903198242188
  - id: hsmetrics_minimum_base_quality
    type: int?
    'sbg:x': -1417.81689453125
    'sbg:y': -1132.09375
  - id: hsmetrics_coverage_cap
    type: int?
    'sbg:x': -1414.290771484375
    'sbg:y': -1262.5513916015625
  - id: prefix
    type: string?
    'sbg:x': -26.909893035888672
    'sbg:y': 1447.054931640625
  - id: vcf_file
    type: File
    'sbg:x': -1381.3795166015625
    'sbg:y': 454.37030029296875
  - id: sample_sex
    type:
      - 'null'
      - type: array
        items: string
        inputBinding:
          position: 0
          prefix: '--sample-sex'
    'sbg:x': -1040.138671875
    'sbg:y': 1257.2900390625
  - id: sample_name
    type:
      type: array
      items: string
      inputBinding:
        position: 0
        prefix: '--sample-name'
    'sbg:x': -611.3065185546875
    'sbg:y': 1129.552734375
  - id: sample_group
    type:
      - 'null'
      - type: array
        items: string
        inputBinding:
          position: 0
          prefix: '--sample-group'
    'sbg:x': -1235.3941650390625
    'sbg:y': 1131.3775634765625
  - id: major_threshold
    type: float?
    'sbg:x': -91.91722106933594
    'sbg:y': 258.0072021484375
  - id: plot_1
    type: boolean?
    'sbg:x': -260.3760070800781
    'sbg:y': 641.5048828125
  - id: json_1
    type: boolean?
    'sbg:x': -312.3473205566406
    'sbg:y': 917.4905395507812
outputs:
  - id: fgbio_collect_duplex_seq_metrics_duplex_family_size_pool_a
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_0/fgbio_collect_duplex_seq_metrics_duplex_family_size
    type:
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_duplex_family_size_pool_a
    'sbg:x': 516.4937744140625
    'sbg:y': -1038.1038818359375
  - id: fgbio_collect_duplex_seq_metrics_duplex_qc_pool_a
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_0/fgbio_collect_duplex_seq_metrics_duplex_qc
    type:
      - 'null'
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_duplex_qc_pool_a
    'sbg:x': 507.3194885253906
    'sbg:y': -1158.8990478515625
  - id: fgbio_collect_duplex_seq_metrics_duplex_pool_a
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_0/fgbio_collect_duplex_seq_metrics_duplex_umi_counts
    type:
      - 'null'
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_duplex_pool_a
    'sbg:x': 510.3775939941406
    'sbg:y': -1284.28125
  - id: fgbio_collect_duplex_seq_metrics_duplex_yield_metrics_pool_a
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_0/fgbio_collect_duplex_seq_metrics_duplex_yield_metrics
    type:
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_duplex_yield_metrics_pool_a
    'sbg:x': 514.9647216796875
    'sbg:y': -1418.837890625
  - id: fgbio_collect_duplex_seq_metrics_family_size_pool_a
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_0/fgbio_collect_duplex_seq_metrics_family_size
    type:
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_family_size_pool_a
    'sbg:x': 516.4937744140625
    'sbg:y': -1547.2781982421875
  - id: fgbio_collect_duplex_seq_metrics_umi_counts_pool_a
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_0/fgbio_collect_duplex_seq_metrics_umi_counts
    type:
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_umi_counts_pool_a
    'sbg:x': 516.4937744140625
    'sbg:y': -1683.3638916015625
  - id: fgbio_collect_duplex_seq_metrics_duplex_family_size_pool_b
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_1/fgbio_collect_duplex_seq_metrics_duplex_family_size
    type:
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_duplex_family_size_pool_b
    'sbg:x': 510.3775939941406
    'sbg:y': -1842.38525390625
  - id: fgbio_collect_duplex_seq_metrics_duplex_qc_pool_b
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_1/fgbio_collect_duplex_seq_metrics_duplex_qc
    type:
      - 'null'
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_duplex_qc_pool_b
    'sbg:x': 508.8485412597656
    'sbg:y': -1998.3485107421875
  - id: fgbio_collect_duplex_seq_metrics_duplex_umi_counts_pool_b
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_1/fgbio_collect_duplex_seq_metrics_duplex_umi_counts
    type:
      - 'null'
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_duplex_umi_counts_pool_b
    'sbg:x': 499.6742248535156
    'sbg:y': -2158.89892578125
  - id: fgbio_collect_duplex_seq_metrics_duplex_yield_metrics_pool_b
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_1/fgbio_collect_duplex_seq_metrics_duplex_yield_metrics
    type:
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_duplex_yield_metrics_pool_b
    'sbg:x': 495.0870666503906
    'sbg:y': -2319.449462890625
  - id: fgbio_collect_duplex_seq_metrics_family_size_pool_b
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_1/fgbio_collect_duplex_seq_metrics_family_size
    type:
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_family_size_pool_b
    'sbg:x': 502.7323303222656
    'sbg:y': -2457.064208984375
  - id: fgbio_collect_duplex_seq_metrics_umi_counts_pool_b
    outputSource:
      - >-
        fgbio_collect_duplex_seq_metrics_1_2_1/fgbio_collect_duplex_seq_metrics_umi_counts
    type:
      - File
      - type: array
        items: File
    label: fgbio_collect_duplex_seq_metrics_umi_counts_pool_b
    'sbg:x': 498.1451721191406
    'sbg:y': -2605.382080078125
  - id: biometrics_minor_csv
    outputSource:
      - biometrics_minor/biometrics_minor_csv
    type:
      - File
      - type: array
        items: File
    'sbg:x': 1108.409912109375
    'sbg:y': 879.7926025390625
  - id: biometrics_minor_json
    outputSource:
      - biometrics_minor/biometrics_minor_json
    type:
      - 'null'
      - File
      - type: array
        items: File
    'sbg:x': 1099.409912109375
    'sbg:y': 734.1456909179688
  - id: biometrics_minor_plot
    outputSource:
      - biometrics_minor/biometrics_minor_plot
    type:
      - 'null'
      - File
      - type: array
        items: File
    'sbg:x': 1092.851806640625
    'sbg:y': 577.2938232421875
  - id: biometrics_minor_sites_plot
    outputSource:
      - biometrics_minor/biometrics_minor_sites_plot
    type:
      - 'null'
      - File
      - type: array
        items: File
    'sbg:x': 1085.1456298828125
    'sbg:y': 460.587646484375
  - id: biometrics_sexmismatch_json
    outputSource:
      - biometrics_sexmismatch/biometrics_sexmismatch_json
    type:
      - 'null'
      - File
      - type: array
        items: File
    'sbg:x': 1105.6673583984375
    'sbg:y': 1000.427490234375
  - id: biometrics_sexmismatch_csv
    outputSource:
      - biometrics_sexmismatch/biometrics_sexmismatch_csv
    type:
      - File
      - type: array
        items: File
    'sbg:x': 1098.1990966796875
    'sbg:y': 1146.0594482421875
  - id: gatk_collect_insert_size_metrics_txt_pool_b
    outputSource:
      - bam_qc_stats_pool_b/gatk_collect_insert_size_metrics_txt
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_insert_size_metrics_txt_pool_b
    'sbg:x': 466.4290771484375
    'sbg:y': -441.6470642089844
  - id: gatk_collect_insert_size_metrics_histogram_pdf_pool_b
    outputSource:
      - bam_qc_stats_pool_b/gatk_collect_insert_size_metrics_histogram_pdf
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_insert_size_metrics_histogram_pdf_pool_b
    'sbg:x': 469.1591796875
    'sbg:y': -308.7266540527344
  - id: gatk_collect_hs_metrics_txt_pool_b
    outputSource:
      - bam_qc_stats_pool_b/gatk_collect_hs_metrics_txt
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_hs_metrics_txt_pool_b
    'sbg:x': 462.23876953125
    'sbg:y': -168.50518798828125
  - id: gatk_collect_hs_metrics_per_target_coverage_txt_pool_b
    outputSource:
      - bam_qc_stats_pool_b/gatk_collect_hs_metrics_per_target_coverage_txt
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_hs_metrics_per_target_coverage_txt_pool_b
    'sbg:x': 463.8892822265625
    'sbg:y': -41.584774017333984
  - id: gatk_collect_hs_metrics_per_base_coverage_txt_pool_b
    outputSource:
      - bam_qc_stats_pool_b/gatk_collect_hs_metrics_per_base_coverage_txt
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_hs_metrics_per_base_coverage_txt_pool_b
    'sbg:x': 470
    'sbg:y': 76.14533233642578
  - id: gatk_collect_alignment_summary_metrics_txt_pool_b
    outputSource:
      - bam_qc_stats_pool_b/gatk_collect_alignment_summary_metrics_txt
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_alignment_summary_metrics_txt_pool_b
    'sbg:x': 476.1522521972656
    'sbg:y': 197.31488037109375
  - id: gatk_collect_insert_size_metrics_txt_pool_a
    outputSource:
      - bam_qc_stats_pool_a/gatk_collect_insert_size_metrics_txt
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_insert_size_metrics_txt_pool_a
    'sbg:x': 869.6942749023438
    'sbg:y': -947.464111328125
  - id: gatk_collect_insert_size_metrics_histogram_pdf_pool_a
    outputSource:
      - bam_qc_stats_pool_a/gatk_collect_insert_size_metrics_histogram_pdf
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_insert_size_metrics_histogram_pdf_pool_a
    'sbg:x': 861.0437622070312
    'sbg:y': -829.8170776367188
  - id: gatk_collect_hs_metrics_txt_pool_a
    outputSource:
      - bam_qc_stats_pool_a/gatk_collect_hs_metrics_txt
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_hs_metrics_txt_pool_a
    'sbg:x': 859.3136596679688
    'sbg:y': -681.0281372070312
  - id: gatk_collect_hs_metrics_per_target_coverage_txt_pool_a
    outputSource:
      - bam_qc_stats_pool_a/gatk_collect_hs_metrics_per_target_coverage_txt
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_hs_metrics_per_target_coverage_txt_pool_a
    'sbg:x': 866.2340698242188
    'sbg:y': -556.460693359375
  - id: gatk_collect_hs_metrics_per_base_coverage_txt_pool_a
    outputSource:
      - bam_qc_stats_pool_a/gatk_collect_hs_metrics_per_base_coverage_txt
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_hs_metrics_per_base_coverage_txt_pool_a
    'sbg:x': 866.2340698242188
    'sbg:y': -421.5125732421875
  - id: gatk_collect_alignment_summary_metrics_txt_pool_a
    outputSource:
      - bam_qc_stats_pool_a/gatk_collect_alignment_summary_metrics_txt
    type:
      - File
      - type: array
        items: File
    label: gatk_collect_alignment_summary_metrics_txt_pool_a
    'sbg:x': 859.3136596679688
    'sbg:y': -296.9450988769531
  - id: biometrics_extract_pickle
    outputSource:
      - biometrics_extract_0_2_11/biometrics_extract_pickle
    type: File
    'sbg:x': -299.2627258300781
    'sbg:y': 357.65496826171875
  - id: biometrics_major_plot
    outputSource:
      - biometrics_major_0_2_11/biometrics_major_plot
    type: File?
    'sbg:x': 533.5308227539062
    'sbg:y': 379.8710021972656
  - id: biometrics_major_json
    outputSource:
      - biometrics_major_0_2_11/biometrics_major_json
    type: File?
    'sbg:x': 372.240478515625
    'sbg:y': 419.2975158691406
  - id: biometrics_major_csv
    outputSource:
      - biometrics_major_0_2_11/biometrics_major_csv
    type: File
    'sbg:x': 354.3193359375
    'sbg:y': 564.4588012695312
steps:
  - id: bam_qc_stats_pool_b
    in:
      - id: input
        source:
          - collapsed_bam
      - id: target_intervals
        source: pool_b_target_intervals
      - id: bait_intervals
        source: pool_b_bait_intervals
      - id: reference
        source: reference
      - id: hsmetrics_minimum_mapping_quality
        source: hsmetrics_minimum_mapping_quality
      - id: hsmetrics_minimum_base_quality
        source: hsmetrics_minimum_base_quality
      - id: hsmetrics_coverage_cap
        source: hsmetrics_coverage_cap
    out:
      - id: gatk_collect_insert_size_metrics_histogram_pdf
      - id: gatk_collect_insert_size_metrics_txt
      - id: gatk_collect_hs_metrics_txt
      - id: gatk_collect_hs_metrics_per_base_coverage_txt
      - id: gatk_collect_hs_metrics_per_target_coverage_txt
      - id: gatk_collect_alignment_summary_metrics_txt
    run: ../bam_qc_stats/bam_qc_stats.cwl
    label: bam_qc_stats_pool_b
    'sbg:x': -45.63414764404297
    'sbg:y': -58.36585235595703
  - id: bam_qc_stats_pool_a
    in:
      - id: input
        source:
          - collapsed_bam
      - id: target_intervals
        source: pool_a_target_intervals
      - id: bait_intervals
        source: pool_a_bait_intervals
      - id: reference
        source: reference
      - id: hsmetrics_minimum_mapping_quality
        source: hsmetrics_minimum_mapping_quality
      - id: hsmetrics_minimum_base_quality
        source: hsmetrics_minimum_base_quality
      - id: hsmetrics_coverage_cap
        source: hsmetrics_coverage_cap
    out:
      - id: gatk_collect_insert_size_metrics_histogram_pdf
      - id: gatk_collect_insert_size_metrics_txt
      - id: gatk_collect_hs_metrics_txt
      - id: gatk_collect_hs_metrics_per_base_coverage_txt
      - id: gatk_collect_hs_metrics_per_target_coverage_txt
      - id: gatk_collect_alignment_summary_metrics_txt
    run: ../bam_qc_stats/bam_qc_stats.cwl
    label: bam_qc_stats_pool_a
    'sbg:x': -79.8152847290039
    'sbg:y': -635.7706909179688
  - id: fgbio_collect_duplex_seq_metrics_1_2_0
    in:
      - id: input
        source: group_reads_by_umi_bam
      - id: intervals
        source: pool_a_bait_intervals
    out:
      - id: fgbio_collect_duplex_seq_metrics_family_size
      - id: fgbio_collect_duplex_seq_metrics_duplex_family_size
      - id: fgbio_collect_duplex_seq_metrics_duplex_yield_metrics
      - id: fgbio_collect_duplex_seq_metrics_umi_counts
      - id: fgbio_collect_duplex_seq_metrics_duplex_qc
      - id: fgbio_collect_duplex_seq_metrics_duplex_umi_counts
    run: >-
      ../command_line_tools/fgbio_collect_duplex_seq_metrics_1.2.0/fgbio_collect_duplex_seq_metrics_1.2.0.cwl
    label: fgbio_collect_duplex_seq_metrics_1.2.0
    'sbg:x': -102.85713958740234
    'sbg:y': -1250.857177734375
  - id: fgbio_collect_duplex_seq_metrics_1_2_1
    in:
      - id: input
        source: group_reads_by_umi_bam
      - id: intervals
        source: pool_b_bait_intervals
    out:
      - id: fgbio_collect_duplex_seq_metrics_family_size
      - id: fgbio_collect_duplex_seq_metrics_duplex_family_size
      - id: fgbio_collect_duplex_seq_metrics_duplex_yield_metrics
      - id: fgbio_collect_duplex_seq_metrics_umi_counts
      - id: fgbio_collect_duplex_seq_metrics_duplex_qc
      - id: fgbio_collect_duplex_seq_metrics_duplex_umi_counts
    run: >-
      ../command_line_tools/fgbio_collect_duplex_seq_metrics_1.2.0/fgbio_collect_duplex_seq_metrics_1.2.0.cwl
    label: fgbio_collect_duplex_seq_metrics_1.2.0
    'sbg:x': -101.767578125
    'sbg:y': -2137.599365234375
  - id: biometrics_minor
    in:
      - id: input
        linkMerge: merge_flattened
        source:
          - biometrics_extract_0_2_11/biometrics_extract_pickle
      - id: minor_threshold
        source: minor_threshold
      - id: prefix
        default: collapsed
        source: prefix
      - id: plot
        default: false
        source: plot
      - id: json
        default: true
        source: json
    out:
      - id: biometrics_minor_csv
      - id: biometrics_minor_json
      - id: biometrics_minor_plot
      - id: biometrics_minor_sites_plot
    run: ../command_line_tools/biometrics_minor/0.2.11/biometrics_minor.cwl
    'sbg:x': 686.5601196289062
    'sbg:y': 571.31689453125
  - id: biometrics_sexmismatch
    in:
      - id: input
        linkMerge: merge_flattened
        source:
          - biometrics_extract_0_2_11/biometrics_extract_pickle
      - id: coverage_threshold
        source: coverage_threshold
      - id: prefix
        default: collapsed
        source: prefix
      - id: json
        source: json
    out:
      - id: biometrics_sexmismatch_csv
      - id: biometrics_sexmismatch_json
    run: >-
      ../command_line_tools/biometrics_sexmismatch/0.2.11/biometrics_sexmismatch.cwl
    'sbg:x': 688.3497924804688
    'sbg:y': 1029.9459228515625
  - id: biometrics_extract_0_2_11
    in:
      - id: sample_bam
        source:
          - collapsed_bam
      - id: sample_sex
        source:
          - sample_sex
      - id: sample_group
        source:
          - sample_group
      - id: sample_name
        source:
          - sample_name
      - id: fafile
        source: reference
      - id: vcf_file
        source: vcf_file
    out:
      - id: biometrics_extract_pickle
    run: ../command_line_tools/biometrics_extract/0.2.11/biometrics_extract.cwl
    'sbg:x': -469.8955078125
    'sbg:y': 493.86566162109375
  - id: biometrics_major_0_2_11
    in:
      - id: input
        source:
          - biometrics_extract_0_2_11/biometrics_extract_pickle
      - id: major_threshold
        source: major_threshold
      - id: prefix
        source: prefix
      - id: plot
        source: plot_1
      - id: json
        source: json_1
    out:
      - id: biometrics_major_csv
      - id: biometrics_major_json
      - id: biometrics_major_plot
    run: ../../cwl-commandlinetools/biometrics_major/0.2.11/biometrics_major.cwl
    'sbg:x': 189.44500732421875
    'sbg:y': 413.921630859375
requirements:
  - class: SubworkflowFeatureRequirement
