name: Pack CWL Files

# Triggers the action on push or pull requests,
# but only for the develop branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  pack_cwls:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install cwltool
        run: |
          python -m pip install toil[cwl]==5.7.1
      - name: Run cwltool --pack for all workflows
        run: |
          echo Removing old packed workflows
          rm -rf ./packed_workflows/*
          echo Packing CWL files...
          find . -name '*.cwl' ! -path '*__packed*' ! -path '*/command_line_tools/*' -type f -print0 -exec sh -c 'cwltool --pack $0 > ${0/.cwl/__packed.cwl}' {} \;
      - name: Validate packed workflows
        run: |
          echo Validating packed workflows...
          find . -name '*__packed.cwl' | xargs -I file cwltool --debug --validate file
      - uses: EndBug/add-and-commit@v4
        with:
          ref: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
